In [35]:
import pandas as pd

df_recipes = pd.read_csv('../data/raw/RAW_recipes.csv')     # Đọc file dữ liệu món ăn từ thư mục raw
df_interactions = pd.read_csv('../data/raw/RAW_interactions.csv')

# Xem tổng quan số lượng dòng và cột
print("Recipes shape :", df_recipes.shape)
print("Interactions shape :", df_interactions.shape)

df_recipes.columns
df_interactions.columns

display(df_recipes.head(1))                                # Hiển thị món
display(df_interactions.head(5))                           # Hiển thị review

df_recipes.dtypes
df_recipes.info()                                           # Kiểm tra các kiểu dữ liệu
df_interactions.dtypes

df_recipes.describe()                                       #Thống kê dữ liệu

Recipes shape : (231637, 12)
Interactions shape : (1132367, 5)

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7

,user_id,recipe_id,date,rating,review
0,38094,40893,2003-02-17,4,Great with a salad. Cooked on top of stove for...
1,1293707,40893,2011-12-21,5,"So simple, so delicious! Great for chilly fall..."
2,8937,44394,2002-12-01,4,This worked very well and is EASY. I used not...
3,126440,85009,2010-02-27,5,I made the Mexican topping and took it to bunk...
4,57222,85009,2011-10-01,5,"Made the cheddar bacon topping, adding a sprin..."

<class 'pandas.DataFrame'>
RangeIndex: 231637 entries, 0 to 231636
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            231636 non-null  str
 1   id              231637 non-null  int64
 2   minutes         231637 non-null  int64
 3   contributor_id  231637 non-null  int64
 4   submitted       231637 non-null  str
 5   tags            231637 non-null  str
 6   nutrition       231637 non-null  str
 7   n_steps         231637 non-null  int64
 8   steps           231637 non-null  str
 9   description     226658 non-null  str
 10  ingredients     231637 non-null  str
 11  n_ingredients   231637 non-null  int64
dtypes: int64(5), str(7)
memory usage: 21.2 MB

,id,minutes,contributor_id,n_steps,n_ingredients
count,231637.000000,2.316370e+05,2.316370e+05,231637.000000,231637.000000
mean,222014.708984,9.398546e+03,5.534885e+06,9.765499,9.051153
std,141206.635626,4.461963e+06,9.979141e+07,5.995128,3.734796
min,38.000000,0.000000e+00,2.700000e+01,0.000000,1.000000
25%,99944.000000,2.000000e+01,5.690500e+04,6.000000,6.000000
50%,207249.000000,4.000000e+01,1.736140e+05,9.000000,9.000000
75%,333816.000000,6.500000e+01,3.982750e+05,12.000000,11.000000
max,537716.000000,2.147484e+09,2.002290e+09,145.000000,43.000000

In [ ]:
df_recipes.isnull().sum()                                   # Kiểm tra dữ liệu bị null
#df['calories'].fillna(df['calories'].mean(), inplace=True)

name                 1
id                   0
minutes              0
contributor_id       0
submitted            0
tags                 0
nutrition            0
n_steps              0
steps                0
description       4979
ingredients          0
n_ingredients        0
dtype: int64

In [ ]:
df_recipes.duplicated().sum()                           # Kiểm tra dữ liệu trùng

np.int64(0)

In [ ]:
df_recipes['num_ingredients'] = df_recipes['ingredients'].apply(len)        #Đếm số nguyên liệu mỗi món
df_recipes['ingredient_list'] = df_recipes['ingredients'].apply(lambda x: x.split(','))


print(df_recipes['num_ingredients'])
#print(df_recipes.iloc[7])

0          93
1          86
2         193
3         186
4         110
         ...
231632    345
231633    205
231634    146
231635    162
231636    104
Name: num_ingredients, Length: 231637, dtype: int64
name                                  backyard style  barbecued ribs
id                                                             67888
minutes                                                          120
contributor_id                                                 10404
submitted                                                 2003-07-30
tags               ['weeknight', 'time-to-make', 'course', 'main-...
nutrition             [1109.5, 83.0, 378.0, 275.0, 96.0, 86.0, 36.0]
n_steps                                                           10
steps              ['in a medium saucepan combine all the ingredi...
description        this recipe is posted by request and was origi...
ingredients        ['pork spareribs', 'soy sauce', 'fresh garlic'...
n_ingredients                                                     22
num_ingredients                                                  365
Name: 7, dtype: object

In [28]:
from collections import Counter

all_ingredients = []

for i in df_recipes['ingredient_list']:
    all_ingredients.extend(i)

Counter(all_ingredients).most_common(10)                    # Tìm nguyên liệu phổ biến nhất

[(" 'salt'", 78127),
 (" 'butter'", 38862),
 (" 'sugar'", 38756),
 (" 'onion'", 35739),
 (" 'eggs'", 28726),
 (" 'water'", 27119),
 (" 'garlic cloves'", 24459),
 (" 'olive oil'", 23934),
 (" 'milk'", 21359),
 (" 'flour'", 19695)]

In [ ]:
import ast
import pandas as pd

df_recipes = pd.read_csv('../data/raw/RAW_recipes.csv')

# Join rating vào df_recipes
# df_recipes = df_recipes.merge(df_interactions[['recipe_id','rating']], left_on = 'id', right_on = 'recipe_id', how='left')
# df_recipes.head(2)

#Convert Nutrition
# Calories  -  TotalFat  -  Sugar  -  Sodium  -  Protein  -  SaturatedFat  -  Carbohydrates

# df_recipes['nutrition'] = df_recipes['nutrition'].apply(ast.literal_eval)
# df_recipes['calories'] = df_recipes['nutrition'].apply(lambda x : x[0])
# df_recipes['fat'] = df_recipes['nutrition'].apply(lambda x : x[1])
# df_recipes['sugar'] = df_recipes['nutrition'].apply(lambda x : x[2])
# df_recipes['sodium'] = df_recipes['nutrition'].apply(lambda x : x[3])
# df_recipes['protein'] = df_recipes['nutrition'].apply(lambda x : x[4])
# df_recipes['sat_fat'] = df_recipes['nutrition'].apply(lambda x : x[5])
# df_recipes['carbs'] = df_recipes['nutrition'].apply(lambda x : x[6])

nutrition_cols = [
    "calories",
    "fat",
    "sugar",
    "sodium",
    "protein",
    "saturated_fat",
    "carbs"
]

df_recipes[nutrition_cols] = pd.DataFrame(
    df_recipes['nutrition'].apply(ast.literal_eval).tolist(),
    index=df_recipes.index
)

df_recipes[nutrition_cols].describe()

,calories,fat,sugar,sodium,protein,saturated_fat,carbs
count,231637.000000,231637.00000,231637.000000,231637.000000,231637.00000,231637.000000,231637.000000
mean,473.942425,36.08070,84.296865,30.147485,34.68186,45.589150,15.560403
std,1189.711374,77.79884,800.080897,131.961589,58.47248,98.235758,81.824560
min,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,174.400000,8.00000,9.000000,5.000000,7.00000,7.000000,4.000000
50%,313.400000,20.00000,25.000000,14.000000,18.00000,23.000000,9.000000
75%,519.700000,41.00000,68.000000,33.000000,51.00000,52.000000,16.000000
max,434360.200000,17183.00000,362729.000000,29338.000000,6552.00000,10395.000000,36098.000000

In [8]:
df_recipes[nutrition_cols].head()
#df_recipes['calories'].hist(bins=50)
df_recipes.head(1)

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients,calories,fat,sugar,sodium,protein,saturated_fat,carbs
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7,51.5,0.0,13.0,0.0,2.0,0.0,4.0

In [ ]:
# Phân tích độ dài instruction
# Feature Engineering

# viết EDA
# Dataset overview
# Missing value analysis
# Ingredient analysis
# Nutrition analysis
# Rating analysis

# Pipeline EDA

# EDA mở rộng
# Ingredient similarity
# Tag distribution